### ISSUE TITLE
Version 1.0 Roadmap

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/backbone.layoutmanager#382]
Our main goals are:

* Finalize the API.
* Polished documentation.
* Finish implementing benchmark suite.
* Extract the core of Backbone.LayoutManager into a separate repository.  
  - This new project will not depend on Underscore or Backbone.
* I'd like to get the project to the point where we can remove the `node/` directory.

Do you have any other ideas that would help make Layout Manager better? Now's the time to ask. =)

If you have any questions please ping one of us:
@tbranyen
@jugglinmike
@SBoudrias
@ssafejava

**Comment by guillaumek** [comment]
+1

**Comment by tbranyen** [comment]
I've been using this project again so I would expect a 1.0 release in the near future.  Within a few months or so.  There isn't much left to do with it.  Just a few API tweaks and I want to add in the methods we're using from Backbone and drop the dependency.  We'll still attach to Backbone if it's available.  If you use something like Browserify you'd do something like:

``` javascript
var Backbone = require('backbone');
Backbone.Layout = require('layoutmanager');
```

**Comment by danstanhope** [comment]
Very cool! Thanks a lot, Tim.

**Comment by guillaumek** [comment]
yes it would be so nice to see it through the 1.0 :100:

**Comment by mhanney** [comment]
+1 for a 1.0 release. I use it everyday in some major projects. Great work.

**Comment by jugglinmike** [comment]
Thanks for your interest, everyone! Keep in mind that 1.0 is just a number--as @tbranyen points out (and as is responsible), the 1.0 release will not include anything too exciting.

**Comment by guillaumek** [comment]
yep that's 1.0 is fair :)

**Comment by jdittrich** [comment]
looking forward, great work!

**Comment by shipengyan** [comment]
er, **ViewManager** is a better name. What do you think? @tbranyen @jugglinmike
@SBoudrias
@ssafejava

**Comment by tbranyen** [comment]
I tagged 1.0, I don't really want to work on LayoutManager anymore and the API is tested and works well enough to not need any major new features. I'm focusing my time on [diffHTML](http://diffhtml.org) now which is a passion-project to improve project and component design by using browser standards.
