### ISSUE TITLE
Remove parent and child/childs views

### ISSUE THREAD

**Issue by djhojd** [tbranyen/backbone.layoutmanager#407]
Hi all,

I've been playing around with Layout Manager for two weeks now and i ran into some difficulties or not.

I have one ParentView and one ChildView. When I try to remove the parent view with .remove() the child html is removed but the instance is still in memory somewhere, I see that with BackBone Eye (firefox) and also with Backbone Debugger (chrome) ... now when I do child.remove() and then parent.remove() both are removed from memory and no trace is left anymore. Am I doing something wrong? or did not understood the correct functionality of LM.View.remove() ???

**Comment by tbranyen** [comment]
Closing until more proof can be produced.
