### ISSUE TITLE
Conveniently load strings with setView

### ISSUE THREAD

**Issue by kofrasa** [tbranyen/backbone.layoutmanager#411]
I have found it useful to be able to render a template string directly with setView.
The current implementation only work with Backbone.Layout objects but very often u may want to just load a string in a section of a view.

Example:
```javascript
var ParentView = Backbone.Layout.extend({
  views: {
    ".title": "Backbone LayoutManager", //here
    ".content": new DocView()
  }
});

var parent = new ParentView();
parent.render();

// somewhere later in the code
parent.setView(".title", "More Awesomeness"); // this fails currently
```
I patched setView to auto-create a Backbone.Layout object when passed a string as the view. The template render function just returns the string as is without any processing. 

Any thoughts, can i go ahead and submit a pull request?

**Comment by tbranyen** [comment]
Closed, please open a PR to continue discussion.
