### ISSUE TITLE
Have a "remove"/"cleanup" event?

### ISSUE THREAD

**Issue by moreofmorris** [tbranyen/backbone.layoutmanager#414]
Hello. I'm trying to write a small extension to LayoutManger for my project and want to keep things as clean as possible. My extension has to do something once the layout has been rendered and once the layout has been removed. It looks like I can listen to the "afterRender" event for my first one, but I don't seem to have anything for remove. Would it possible to have LayoutManager trigger a remove event when the layout has been removed? Or am I missing something?

At the moment, I'm doing the following... Which means I'm having to duplicate LayoutManager code:

```
Backbone.Layout.prototype.remove = function() {

  // MY CODE GOES HERE

  // Force remove itself from its parent.
  Backbone.Layout._removeView(this, true);
  // Call the original remove function.
  return this._remove.apply(this, arguments);
};
```

Is there already a better way? Or could you simply add a "remove"/"cleanup" event that gets triggered?

**Comment by tbranyen** [comment]
Cleanup event has been added into master, it will exist in the next release: 0.9.7.
