### ISSUE TITLE
renderViews does not maintain order.

### ISSUE THREAD

**Issue by tbranyen** [tbranyen/backbone.layoutmanager#416]
This was discovered during a conversation on the #backbone-boilerplate irc channel.

Breaking test forthcoming.

**Comment by ambiguousFoo** [comment]
I love this extension, but in our implementation this one bug is just driving me crazy.  Looking forward to a fix.  Great work so far!

**Comment by tbranyen** [comment]
Was unable to make a failing test: https://github.com/tbranyen/backbone.layoutmanager/pull/472

Any help narrowing down this problem would be great!

**Comment by tbranyen** [comment]
Closing via https://github.com/tbranyen/backbone.layoutmanager/pull/472
