### ISSUE TITLE
childview and rendering 

### ISSUE THREAD

**Issue by jbluedelta** [tbranyen/backbone.layoutmanager#451]
My userdetailview.js file

 

define(
        [ 'modules/baseClass],

        function(BaseClass) {

            // Create a new module

            //Create Model

            //Create View
            UserDetails.Views.Content = Backbone.View
                    .extend({
                        template : 

                        initialize : function() {
                            this.model = new UserDetails.Model();
                        },

                        events : {

                        },

                        render : function(LayOut) {

                            return LayOut(this).render().then(this.pageReady);
                        },

                        pageReady : function() {
                        },

                    });

                    UserDetails.activate = function() {
                        app.router.navigate('UserDetails', true);
                    };

                    UserDetails.configureRouting = function() {
                        app.router.route('UserDetails', 'UserDetails',
                        function() {
                            layoutmanager.setView('#content',
                                    new UserDetails.Views.Content())
                                    .render();
                        });
                    };

                    return UserDetails;

        });

My adminview.js

define([
    'modules/baseclass',
    'modules/UserDetail'
],

function(BaseClass, UserDetails) {

    UserDetail.Views.Content = UserDetail.Views.Content.extend({
            render:function(){
                console.log("rendering");
                UserDetail.Views.Content.prototype.render();
            }
    });

    //create admin model

    //admin view
    AdminView.Views.Content = Backbone.View.extend({

        template: "admin-template",

        events: {
        },

        initialize: function() {
            this.model = new AdminModel.Model();
        },

        render: function(manage) {
            return manage(this).render().then(this.pageReady);
        },

        pageReady: function() {

            });

        },

    AdminView.activate = function() {
        app.router.navigate('adminview', true);
    };

    AdminView.configureRouting = function() {
        app.router.route('adminview', 'adminview', function() {
            layoutmanager.setView('#content', new AdminView.Views.Content()).render();
            layoutmanager.setView('#userDetials', new UserDetials.Views.Content()).render();

        });
    };

    if(app.router && app.router.route) {
        AdminView.configureRouting();
    }

    return AdminView;
});

I want to display userview inside adminview and override one of the events of userview inside adminview

**Comment by tbranyen** [comment]
Hi, this is an old support issue, if you still require help, please join our Gitter channel in the README.
