### ISSUE TITLE
View/Template Helper

### ISSUE THREAD

**Issue by danstanhope** [tbranyen/backbone.layoutmanager#456]
Hey guys,

It would be great if there was a way to blend in some view/template helpers.

myView = Backbone.View.extend({
    template : "my_view",
    templateHelper : someHelperFunctions
...

If the templateHelper attribute is defined, extend the template's data with this object literal.

Would be really handy, rather than having to normalize your view data elsewhere.

Thoughts?

Thanks!
Dan

**Comment by tbranyen** [comment]
Not all template engines work this way, but I'm glad you found a way to extend LayoutManager to work for your use case!
