### ISSUE TITLE
Uncaught TypeError: Cannot read property 'renderDeferred' of undefined 

### ISSUE THREAD

**Issue by b3457m0d3** [tbranyen/backbone.layoutmanager#458]
i am trying to load in a subview by adding it to the layout, 
`return view.render().__manager__.renderDeferred; ` is the line thats throwing the error, in the `renderViews()` function.  im setting a view using `setView()` and calling `renderViews()` in the layout's `afterRender` function...  can anyone spare any insight as to what may be happening here?

**Comment by tbranyen** [comment]
Hi, without a reduced test case or any code we won't be able to help.  As this is an old support issue I'm going to close.  If you still need assistance, please join our Gitter room in the README.
