### ISSUE TITLE
Add cleanup event

### ISSUE THREAD

**Issue by jhoegee** [tbranyen/backbone.layoutmanager#460]
I like to add a cleanup event, it should be triggered at the same time the cleanup method is called in  view.

In this way i can write cleaner code which can be maintained easier.
e.g

``` javascript
var main = new Backbone.Layout({
// some code
  afterRender: function () {
          this.translationControl = this.createTranslationControl(this.model, this.$("#PropertyDisplayNameInput"), "TranslatablePropertyName");
}

  cleanup: function(){
     this.translationControl.destroy();
  }
});
```

In need to implement to call the destroy of the translationControl.

What i like to do is to register this function on a cleanup event, so that my translation control gets destroyed, without implementing it in each cleanup() method for each view

like:

``` javascript
createTranslationControl: function(model, element, translatablePropertyName, options)
		{
			var translationControl = new TranslationControl(model.cwsAdapter.businessObject(), element, translatablePropertyName, options);
			this.on("beforeRender cleanup", function() { translationControl.destroy() });
			return translationControl;
		}
```

**Comment by tbranyen** [comment]
Merged! Thanks again!
