### ISSUE TITLE
In FireFox 35.1 the beforeRender is called twice 

### ISSUE THREAD

**Issue by jhoegee** [tbranyen/backbone.layoutmanager#463]
I have defined a beforeRender my extended view from the backbone.layoutmanager and noticed that in FireFox 35.1 the beforeRender is called twice.

**Comment by jugglinmike** [comment]
That sounds like a bug! Can you share a reduced script that demonstrates the problem?

**Comment by jhoegee** [comment]
This problem is caused in FireFox by the cancelAnimationFrame(), which caused that the finish() is still called once, while canceled.

Scenario
created a mainView and and childView, 
The childView should take longer to render than the mainView
render both views quckly after each other.
The mainView will finish earlier qnd it will cancel the childviews RAF using cancelAnimationFrame()
and call the finish for the child directly (from _registerWithRAF)
This will work fine in Chrome, but in FireFox, the finish() will still be handled from the RAF!

Trace Chrome:
Register RAF: MainView
Register RAF: ChildView
Finish: MainView
render: MainView
Cancel RAF: ChildView
Register RAF: ChildView
Finish: ChildView # directly called from _registerWithRAF()
render: ChildView

Trace FireFox:
Register RAF: MainView
Register RAF: ChildView
Finish: MainView
render: MainView
Cancel RAF: ChildView
Register RAF: ChildView
Finish: ChildView  # directly called from _registerWithRAF() 
render: ChildView
Finish: ChildView  # Called from the RAF !!!!!!!
render: ChildView

If added a test in test set 
// https://github.com/tbranyen/backbone.layoutmanager/issues/463
asyncTest("Test if before render is called twice in FireFox, because cancelAnimationFrame is not working properly", 1, function() {
	var count = { before: 0 };
	
	var ChildView = Backbone.Layout.extend({
		viewName: 'ChildView',

		beforeRender: function(){
			count.before++;
		},

		render: function(){
			wait();
		},

		wait : function() {
			for (var i = 0; i++; i < 9999999999999) {
				var c;
				c += Math.cos(12) * Math.sin(4) / Math.PI;
			}
		},
	});
	var childView = new ChildView();
	
	var MainView = Backbone.Layout.extend({
		viewName: 'MainView',

		beforeRender: function() {
			this.addChildView();
		},
		
		addChildView: function() {
			new Backbone.Layout().insertView(childView).render();
		},
	});
	
	new MainView({ model: new Backbone.Model() }).render();
	childView.render().then(function() {
		childView.once("beforeRender", function(){
			equal(count.before, 1, "beforeRender is called more than once");
			start();
		})
	});
	
});

**Comment by jhoegee** [comment]
i change the test a little bit to be able to stop the test for Chrome. (the second childView render does not come for Chrome)
// https://github.com/tbranyen/backbone.layoutmanager/issues/463
asyncTest("Test if before render is called twice in FireFox, because cancelAnimationFrame is not working properly", 1, function() {
	var count = { before: 0 };
	
	var ChildView = Backbone.Layout.extend({
		viewName: 'ChildView',

		beforeRender: function(){
			count.before++;
		},

		render: function(){
			wait();
		},

		wait : function() {
			for (var i = 0; i++; i < 9999999999999) {
				var c;
				c += Math.cos(12) * Math.sin(4) / Math.PI;
			}
		},
	});
	var childView = new ChildView();
	
	var MainView = Backbone.Layout.extend({
		viewName: 'MainView',

		beforeRender: function() {
			this.addChildView();
		},
		
		addChildView: function() {
			new Backbone.Layout().insertView(childView).render();
		},
	});
	
	new MainView({ model: new Backbone.Model() }).render();
	childView.render().then(function() {
	    var timeoutID = setTimeout(stopAndValidateTest, 400);
		childView.once("beforeRender", function(){
			clearTimeout(timeoutID);
			stopAndValidateTest();
		});
	});
	
	function stopAndValidateTest()
	{
		equal(count.before, 1, "beforeRender is called more than once");
		start();
	}
	
});

**Comment by jhoegee** [comment]
issue can be closed, it was not caused by FireFox, but cause in my own application code, where the child view was rendered 2 times.
