### ISSUE TITLE
bindAll errors in initialize

### ISSUE THREAD

**Issue by designermonkey** [tbranyen/backbone.layoutmanager#465]
I'm trying to `_.bindAll()` to functions within my view, as I've been taught to do in Backbone, yet it errors every time I use it.

```
Uncaught TypeError: Cannot read property 'bind' of undefined
```

Any ideas? I can walk through it if needed.

**Comment by tbranyen** [comment]
No idea, definitely not related to LayoutManager.  Can you join Gitter (found in our README) that's where we are handling general support.

**Comment by designermonkey** [comment]
Seems to work intermittently. Weird.
