### ISSUE TITLE
jQuery may not be defined yet...

### ISSUE THREAD

**Issue by designermonkey** [tbranyen/backbone.layoutmanager#466]
Heya,

Coming across a slight problem where jQuery, and specifically it's Deferred object isn't defined in my build at runtime.

My app defines `Backbone.$` *after* all the bower components are loaded, so LayoutManager has no reference to it when defining the `defaultOptions`, and in particular, the definition of `deferred`. This obviously means that all calls to render fail miserable :(

Can I suggest not relying on `Backbone.$`, but instead follow the way Backbone itself does it with `(window.jQuery || window.Zepto || window.ender || window.$)`?

I mean at line 31 of course :)

What do you think?

**Comment by tbranyen** [comment]
Hrm, I don't know how we'd do this.  We locally require and scope `$` to avoid global lookups.  We don't rely on `Backbone.$`.  See: https://github.com/tbranyen/backbone.layoutmanager/blob/master/backbone.layoutmanager.js#L982-L984

If you can think of a way to support your use case, please submit a PR.

**Comment by designermonkey** [comment]
https://github.com/tbranyen/backbone.layoutmanager/blob/master/backbone.layoutmanager.js#L26

and 

https://github.com/tbranyen/backbone.layoutmanager/blob/master/backbone.layoutmanager.js#L31

jQuery is passed from Backbone. For me specifically, it is line 31.
