### ISSUE TITLE
Overriding render method

### ISSUE THREAD

**Issue by designermonkey** [tbranyen/backbone.layoutmanager#467]
I have a Backbone plugin in development for Google Maps, which is not requiring LayoutManager by default, as I think the dependency unnecessary.

To test it, I'm developing in situ of a project that does use LayoutManager, as it's the best software out there for managing complex projects. I have hit a snag though, that I think should be filed as a bug.

The plugin's views have their own `render` method, as they have to render the actual `google.maps` objects. This causes them to never render, no matter what settings I use for LayoutManager.

I've tried `manage: false`, and included `keep: true`, but no matter what, the render fails.

When I inspect the function footprint, it seems that even though I am extending `Backbone.Layout`, the render method is overwritten **after** the extend. This is an anti-pattern IMO, as all the patching and extending that LayoutManager does should happen before a developer extends the core classes.

Is there any way to ensure my render methods are left untouched?

This also leads me to another question... (sorry)

Would LayoutManager not be better suited to clone `Backbone.View`, and allow the use of native views as well as layouts? That way any other plugins utilising views are free to implement their own functionality and not be overridden.

**Comment by designermonkey** [comment]
I've found it at line `894`.

Shouldn't this not be happening if `manage: false`?

Wouldn't it be better to only require the Layout render method to expect every sub-view to return itself so the render chain of Layout can continue?

**Comment by designermonkey** [comment]
Ok, so I had `manage: true` set globally. Switched that off, but now I find I can't nest a native `View` using `setView`.

Any reason for this? Would it be possible to allow this so that native View `render` functions can be automatically initiated too?

**Comment by tbranyen** [comment]
@designermonkey you can set `manage: true` on specific View instances.  That should fix your issue re: not using a global flag.

**Comment by designermonkey** [comment]
Ok, closing this.
