### ISSUE TITLE
Using render().promise() with bluebird

### ISSUE THREAD

**Issue by SimenB** [tbranyen/backbone.layoutmanager#483]
If I send the promise from `view.render().promise()` into `BluebirdPromise.resolve()` it crashes Chrome. Any idea why?

See jsbin: https://jsbin.com/xaxeta/6/edit?js,console,output

Just remove the comments in `Promise.resolve`, and it'll crash

Using `jQuery.Deferred()` and `jQuery.Deferred().promise()` (which I think is what happens under the hood) directly works fine with bluebird

**Comment by SimenB** [comment]
Based on feedback in petkaantonov/bluebird#728, created the PR #484 for this

**Comment by tbranyen** [comment]
> @SimenB hrm, i hate to say this, but i feel like what you did may be overkill. what if we just did:
// Proxy `then` for easier invocation.
then: function(success, failure) {
  return this.promise().then(success, failure);
},


https://gitter.im/tbranyen/backbone.layoutmanager?at=55d267933d8917890c16782b

**Comment by SimenB** [comment]
@tbranyen Nope, doesn't work unfortunately, still hangs
