### ISSUE TITLE
npm peerDependency warning due to invalid (?) jquery semver.

### ISSUE THREAD

**Issue by teehemkay** [tbranyen/backbone.layoutmanager#485]
npm (both the 2.x and 3.x versions) gives the following warning even though jquery is installed at the app level.

`npm WARN EPEERINVALID layoutmanager@0.9.7 requires a peer of jquery@* but none was installed.`

My guess is that the '*' used to specify acceptable jquery version in the peerDependencies property is not a valid semver.

**Comment by SBoudrias** [comment]
No, peerDependencies are not supported by npm anymore. So they're just warning you LayoutManager is expecting jQuery to be installed as a dependency of your project.

**Comment by teehemkay** [comment]
Actually, I'm using `npm@3.x` which does support peerDependencies. It just that it won't install them (like `npm@2.x` does) as this responsibility is left up to the app.

The warning I'm seeing is actually correct and does not have anything to do with the "*" specified as the the `jquery` semver in the `peerDependencies` property.

The problem is that even though there was a compatible jquery dependency installed at the app level upper in the dependency hierarchy, it was manually installed and not actually specified in the app package.json `dependencies` property.
