### ISSUE TITLE
layoutmanager.org domain rname egistration has expired

### ISSUE THREAD

**Issue by teehemkay** [tbranyen/backbone.layoutmanager#487]
Title says it all...

**Comment by andreieftimie** [comment]
Content was redirected to this wiki: https://github.com/tbranyen/backbone.layoutmanager/wiki

(According to https://web.archive.org/web/20141228101127/https://github.com/tbranyen/backbone.layoutmanager/wiki )

**Comment by teehemkay** [comment]
Problem is there are still several links layoutmanager.org displayed prominently in the home page of the repository @ https://github.com/tbranyen/backbone.layoutmanager/

**Comment by tbranyen** [comment]
This has been fixed FYI. Sorry I let it expire, was moving across the country and haven't really been paying attention.
