### ISSUE TITLE
Nested views: Using views object problem

### ISSUE THREAD

**Issue by huang-x-h** [tbranyen/backbone.layoutmanager#495]
View the Wiki examples show how to using`views` object

    Backbone.Layout.extend({
      views: {
        "header": new HeaderView(),
        "section": new ContentView(),
        "footer": new FooterView()
      }
    });

See the code, `views` is defined in the `prototype`, so when reload this view (first step remove this view instance, then add another this view instance), it will be broken, because in the first step view remove will change the prototype `views`, so in the second step `views` property was empty object, then no subViews render.

The `views` property should be in instance not in proptype, every view instances should be have one `views` not share with each other.

I write a exmaple code, view [Plunkr](http://embed.plnkr.co/zIkTpwoCaZyzBC8fbbLw/)

    var GrandChildView = Backbone.Layout.extend({
      tagName: 'button',
      events: {
        'click': 'onClick'
      },

      afterRender: function() {
        this.$el.text('Click me');
      },

      onClick: function() {
        alert('GrantChild click');
      }
    });

    var ChildView = Backbone.Layout.extend({
      views: {
        '': new GrandChildView()
      }
    });

    var ParentView = Backbone.Layout.extend({
      el: '#content',
      views: {
        '': new ChildView()
      }
    });
    
    var parentView = new ParentView().render();

    function reload() {
      parentView.setView(new ChildView());
      // the GrandChildView does render anymore.
    }

**Comment by tbranyen** [comment]
Right, it's intentionally limited (by how JavaScript prototypes work), if you need more power use `setViews` instead. I never used that declarative syntax on anything substantial, but it works fine in for one off demos as it's nicer than having to call `setViews` all the time.
