### ISSUE TITLE
Question: can layout manager catch jquery custom events?

### ISSUE THREAD

**Issue by bboydflo** [tbranyen/backbone.layoutmanager#496]
Hi, I am using the eternicode-datepicker plugin that triggers a custom "hide" event on the specific element the plugin was called. That doesn't seem to be caught by the layout manager. 

Example:

`events: {
    'click td.datepicker': 'showDatePicker',
    'hide td': 'processEvent',
    'hide': 'processEvent'
  },`

Is that something I am doing wrong?

**Comment by tbranyen** [comment]
LayoutManager doesn't do anything to muck with jQuery binding events, maybe it's a problem with Backbone?

**Comment by bboydflo** [comment]
I fixed the issue so far by using aliasify (https://github.com/benbria/aliasify) which replaces all backbone requires to require the latest backbone v 1.2.3. 

I am not sure why backbone layout manager still uses Backbone 1.1.2

**Comment by tbranyen** [comment]
It doesn't, bump your version of it to 1.0.0
